name: d8-sandbox
recipe: drupal8
config:
  php: '7.4'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  drush: ^9
  xdebug: false
  drupal: true
  config:
    database: drupal8
    username: drupal8
    password: drupal8
    host: database
    port: 3306
proxy:
  adminer:
    - adminer.d8-sandbox.lndo.site
services:
  appserver:
    build:
      - composer install
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: /bin/s6-svscan /etc/services.d
    portforward: true
events:
  post-start:
    - /bin/bash /app/scripts/drupal-install.sh
tooling:
  drush:
    cmd: vendor/bin/drush
